# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2499f6f7cb1ad142194b50212c4804ce799c5e3af9a7b214856a0735aa23091291c12499095c9a076a14df7b8bc9391172bbfe4c217693f563909307c3cd407e

test:
  secret_key_base: 6419c4f76f78ae3b1aa14f4e8aa9e95e9f6a5559cfdc723fffcbd6de038206473215c3c8b093a0b45279a8ebf494bb3a07ba6996499df7b316e25b42fce8c49f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
